### ISSUE TITLE
Add environmental variable to expose current commit hash

### ISSUE THREAD

**Issue by heitzer-dpm** [payloadcms/plugin-cloud#5]
Hi, It would be great to have access to the currently deployed commit hash via env variable, e.g. PAYLOAD_CLOUD_COMMIT.
This way one could display or use it to identify the deployed version when collecting bug reports and the like.

**Comment by denolfe** [comment]
Thanks for the feature request. This is likely something we can get to. Moving this repo to the [monorepo](https://github.com/payloadcms/payload/tree/main/packages/plugin-cloud)
